# Generated by Django 4.0.3 on 2023-12-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_recordofsale_remove_automobilevo_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.URLField(default='http://example.com', unique=True),
        ),
    ]
