# Generated by Django 4.0.3 on 2023-12-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_automobilevo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.URLField(default='automobile', unique=True),
        ),
    ]
